<?php
if ( !defined ('TYPO3_MODE') ) {
	die ( 'Access denied.' );
}

$flagsFolderOrSpritePrefix = version_compare(TYPO3_branch, '7.1', '>=') ? (version_compare(TYPO3_branch, '7.6', '>=') ? 'flags-' : 'EXT:core/Resources/Public/Icons/Flags/') : 'EXT:t3skin/images/flags/';
$flagsImageExtension = version_compare(TYPO3_branch, '7.6', '>=') ? '' : '.png';

return [
	'ctrl' => [
		'title'	=> 'LLL:EXT:ecom_toolbox/Resources/Private/Language/locallang_db.xlf:tx_ecomtoolbox_domain_model_language',
		'label' => 'title',
		'label_alt' => 'flag',
		'label_alt_force' => TRUE,
		'tstamp' => 'tstamp',
		'rootLevel' => 1,
		'crdate' => 'crdate',
		'cruser_id' => 'cruser_id',
		'default_sortby' => 'ORDER BY title',
		'dividers2tabs' => TRUE,
		'typeicon_column' => 'flag',
		'typeicon_classes' => [
			'default' => 'extensions-ecomtoolbox-language',
			'mask' => 'flags-###TYPE###'
		],
		'searchFields' => 'title,sys_language,flag,',
		'iconfile' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath( 'ecom_toolbox' ) . 'Resources/Public/Icons/tx_ecomtoolbox_domain_model_language.png'
	],
	'interface' => [
		'showRecordFieldList' => 'title, sys_language, flag',
	],
	'types' => [
		'1' => [ 'showitem' => 'title, sys_language, flag' ]
	],
	'palettes' => [],
	'columns' => [
		'title' => [
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.language',
			'config' => [
				'type' => 'input',
				'size' => '35',
				'max' => '80',
				'eval' => 'trim,required'
			]
		],
		'sys_language' => [
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_tca.xlf:sys_language',
			'config' => [
				'type' => 'select',
				'foreign_table' => 'sys_language',
				'foreign_table_where' => 'ORDER BY sys_language.title',
				'items' => [
					[ 'LLL:EXT:lang/locallang_general.xlf:LGL.allLanguages', -1 ],
					[ 'LLL:EXT:lang/locallang_general.xlf:LGL.default_value', 0 ]
				]
			]
		],
		'flag' => [
			'label' => 'LLL:EXT:lang/locallang_tca.xlf:sys_language.flag',
			'config' => [
				'type' => 'select',
				'items' => [
					[ '', '', '' ],
					[ 'multiple', 'multiple', $flagsFolderOrSpritePrefix . 'multiple' . $flagsImageExtension ],
					[ 'ad', 'ad', $flagsFolderOrSpritePrefix . 'ad' . $flagsImageExtension ],
					[ 'ae', 'ae', $flagsFolderOrSpritePrefix . 'ae' . $flagsImageExtension ],
					[ 'af', 'af', $flagsFolderOrSpritePrefix . 'af' . $flagsImageExtension ],
					[ 'ag', 'ag', $flagsFolderOrSpritePrefix . 'ag' . $flagsImageExtension ],
					[ 'ai', 'ai', $flagsFolderOrSpritePrefix . 'ai' . $flagsImageExtension ],
					[ 'al', 'al', $flagsFolderOrSpritePrefix . 'al' . $flagsImageExtension ],
					[ 'am', 'am', $flagsFolderOrSpritePrefix . 'am' . $flagsImageExtension ],
					[ 'an', 'an', $flagsFolderOrSpritePrefix . 'an' . $flagsImageExtension ],
					[ 'ao', 'ao', $flagsFolderOrSpritePrefix . 'ao' . $flagsImageExtension ],
					[ 'ar', 'ar', $flagsFolderOrSpritePrefix . 'ar' . $flagsImageExtension ],
					[ 'as', 'as', $flagsFolderOrSpritePrefix . 'as' . $flagsImageExtension ],
					[ 'at', 'at', $flagsFolderOrSpritePrefix . 'at' . $flagsImageExtension ],
					[ 'au', 'au', $flagsFolderOrSpritePrefix . 'au' . $flagsImageExtension ],
					[ 'aw', 'aw', $flagsFolderOrSpritePrefix . 'aw' . $flagsImageExtension ],
					[ 'ax', 'ax', $flagsFolderOrSpritePrefix . 'ax' . $flagsImageExtension ],
					[ 'az', 'az', $flagsFolderOrSpritePrefix . 'az' . $flagsImageExtension ],
					[ 'ba', 'ba', $flagsFolderOrSpritePrefix . 'ba' . $flagsImageExtension ],
					[ 'bb', 'bb', $flagsFolderOrSpritePrefix . 'bb' . $flagsImageExtension ],
					[ 'bd', 'bd', $flagsFolderOrSpritePrefix . 'bd' . $flagsImageExtension ],
					[ 'be', 'be', $flagsFolderOrSpritePrefix . 'be' . $flagsImageExtension ],
					[ 'bf', 'bf', $flagsFolderOrSpritePrefix . 'bf' . $flagsImageExtension ],
					[ 'bg', 'bg', $flagsFolderOrSpritePrefix . 'bg' . $flagsImageExtension ],
					[ 'bh', 'bh', $flagsFolderOrSpritePrefix . 'bh' . $flagsImageExtension ],
					[ 'bi', 'bi', $flagsFolderOrSpritePrefix . 'bi' . $flagsImageExtension ],
					[ 'bj', 'bj', $flagsFolderOrSpritePrefix . 'bj' . $flagsImageExtension ],
					[ 'bm', 'bm', $flagsFolderOrSpritePrefix . 'bm' . $flagsImageExtension ],
					[ 'bn', 'bn', $flagsFolderOrSpritePrefix . 'bn' . $flagsImageExtension ],
					[ 'bo', 'bo', $flagsFolderOrSpritePrefix . 'bo' . $flagsImageExtension ],
					[ 'br', 'br', $flagsFolderOrSpritePrefix . 'br' . $flagsImageExtension ],
					[ 'bs', 'bs', $flagsFolderOrSpritePrefix . 'bs' . $flagsImageExtension ],
					[ 'bt', 'bt', $flagsFolderOrSpritePrefix . 'bt' . $flagsImageExtension ],
					[ 'bv', 'bv', $flagsFolderOrSpritePrefix . 'bv' . $flagsImageExtension ],
					[ 'bw', 'bw', $flagsFolderOrSpritePrefix . 'bw' . $flagsImageExtension ],
					[ 'by', 'by', $flagsFolderOrSpritePrefix . 'by' . $flagsImageExtension ],
					[ 'bz', 'bz', $flagsFolderOrSpritePrefix . 'bz' . $flagsImageExtension ],
					[ 'ca', 'ca', $flagsFolderOrSpritePrefix . 'ca' . $flagsImageExtension ],
					[ 'catalonia', 'catalonia', $flagsFolderOrSpritePrefix . 'catalonia' . $flagsImageExtension ],
					[ 'cc', 'cc', $flagsFolderOrSpritePrefix . 'cc' . $flagsImageExtension ],
					[ 'cd', 'cd', $flagsFolderOrSpritePrefix . 'cd' . $flagsImageExtension ],
					[ 'cf', 'cf', $flagsFolderOrSpritePrefix . 'cf' . $flagsImageExtension ],
					[ 'cg', 'cg', $flagsFolderOrSpritePrefix . 'cg' . $flagsImageExtension ],
					[ 'ch', 'ch', $flagsFolderOrSpritePrefix . 'ch' . $flagsImageExtension ],
					[ 'ci', 'ci', $flagsFolderOrSpritePrefix . 'ci' . $flagsImageExtension ],
					[ 'ck', 'ck', $flagsFolderOrSpritePrefix . 'ck' . $flagsImageExtension ],
					[ 'cl', 'cl', $flagsFolderOrSpritePrefix . 'cl' . $flagsImageExtension ],
					[ 'cm', 'cm', $flagsFolderOrSpritePrefix . 'cm' . $flagsImageExtension ],
					[ 'cn', 'cn', $flagsFolderOrSpritePrefix . 'cn' . $flagsImageExtension ],
					[ 'co', 'co', $flagsFolderOrSpritePrefix . 'co' . $flagsImageExtension ],
					[ 'cr', 'cr', $flagsFolderOrSpritePrefix . 'cr' . $flagsImageExtension ],
					[ 'cs', 'cs', $flagsFolderOrSpritePrefix . 'cs' . $flagsImageExtension ],
					[ 'cu', 'cu', $flagsFolderOrSpritePrefix . 'cu' . $flagsImageExtension ],
					[ 'cv', 'cv', $flagsFolderOrSpritePrefix . 'cv' . $flagsImageExtension ],
					[ 'cx', 'cx', $flagsFolderOrSpritePrefix . 'cx' . $flagsImageExtension ],
					[ 'cy', 'cy', $flagsFolderOrSpritePrefix . 'cy' . $flagsImageExtension ],
					[ 'cz', 'cz', $flagsFolderOrSpritePrefix . 'cz' . $flagsImageExtension ],
					[ 'de', 'de', $flagsFolderOrSpritePrefix . 'de' . $flagsImageExtension ],
					[ 'dj', 'dj', $flagsFolderOrSpritePrefix . 'dj' . $flagsImageExtension ],
					[ 'dk', 'dk', $flagsFolderOrSpritePrefix . 'dk' . $flagsImageExtension ],
					[ 'dm', 'dm', $flagsFolderOrSpritePrefix . 'dm' . $flagsImageExtension ],
					[ 'do', 'do', $flagsFolderOrSpritePrefix . 'do' . $flagsImageExtension ],
					[ 'dz', 'dz', $flagsFolderOrSpritePrefix . 'dz' . $flagsImageExtension ],
					[ 'ec', 'ec', $flagsFolderOrSpritePrefix . 'ec' . $flagsImageExtension ],
					[ 'ee', 'ee', $flagsFolderOrSpritePrefix . 'ee' . $flagsImageExtension ],
					[ 'eg', 'eg', $flagsFolderOrSpritePrefix . 'eg' . $flagsImageExtension ],
					[ 'eh', 'eh', $flagsFolderOrSpritePrefix . 'eh' . $flagsImageExtension ],
					[ 'england', 'england', $flagsFolderOrSpritePrefix . 'england' . $flagsImageExtension ],
					[ 'er', 'er', $flagsFolderOrSpritePrefix . 'er' . $flagsImageExtension ],
					[ 'es', 'es', $flagsFolderOrSpritePrefix . 'es' . $flagsImageExtension ],
					[ 'et', 'et', $flagsFolderOrSpritePrefix . 'et' . $flagsImageExtension ],
					[ 'europeanunion', 'europeanunion', $flagsFolderOrSpritePrefix . 'europeanunion' . $flagsImageExtension ],
					[ 'fam', 'fam', $flagsFolderOrSpritePrefix . 'fam' . $flagsImageExtension ],
					[ 'fi', 'fi', $flagsFolderOrSpritePrefix . 'fi' . $flagsImageExtension ],
					[ 'fj', 'fj', $flagsFolderOrSpritePrefix . 'fj' . $flagsImageExtension ],
					[ 'fk', 'fk', $flagsFolderOrSpritePrefix . 'fk' . $flagsImageExtension ],
					[ 'fm', 'fm', $flagsFolderOrSpritePrefix . 'fm' . $flagsImageExtension ],
					[ 'fo', 'fo', $flagsFolderOrSpritePrefix . 'fo' . $flagsImageExtension ],
					[ 'fr', 'fr', $flagsFolderOrSpritePrefix . 'fr' . $flagsImageExtension ],
					[ 'ga', 'ga', $flagsFolderOrSpritePrefix . 'ga' . $flagsImageExtension ],
					[ 'gb', 'gb', $flagsFolderOrSpritePrefix . 'gb' . $flagsImageExtension ],
					[ 'gd', 'gd', $flagsFolderOrSpritePrefix . 'gd' . $flagsImageExtension ],
					[ 'ge', 'ge', $flagsFolderOrSpritePrefix . 'ge' . $flagsImageExtension ],
					[ 'gf', 'gf', $flagsFolderOrSpritePrefix . 'gf' . $flagsImageExtension ],
					[ 'gh', 'gh', $flagsFolderOrSpritePrefix . 'gh' . $flagsImageExtension ],
					[ 'gi', 'gi', $flagsFolderOrSpritePrefix . 'gi' . $flagsImageExtension ],
					[ 'gl', 'gl', $flagsFolderOrSpritePrefix . 'gl' . $flagsImageExtension ],
					[ 'gm', 'gm', $flagsFolderOrSpritePrefix . 'gm' . $flagsImageExtension ],
					[ 'gn', 'gn', $flagsFolderOrSpritePrefix . 'gn' . $flagsImageExtension ],
					[ 'gp', 'gp', $flagsFolderOrSpritePrefix . 'gp' . $flagsImageExtension ],
					[ 'gq', 'gq', $flagsFolderOrSpritePrefix . 'gq' . $flagsImageExtension ],
					[ 'gr', 'gr', $flagsFolderOrSpritePrefix . 'gr' . $flagsImageExtension ],
					[ 'gs', 'gs', $flagsFolderOrSpritePrefix . 'gs' . $flagsImageExtension ],
					[ 'gt', 'gt', $flagsFolderOrSpritePrefix . 'gt' . $flagsImageExtension ],
					[ 'gu', 'gu', $flagsFolderOrSpritePrefix . 'gu' . $flagsImageExtension ],
					[ 'gw', 'gw', $flagsFolderOrSpritePrefix . 'gw' . $flagsImageExtension ],
					[ 'gy', 'gy', $flagsFolderOrSpritePrefix . 'gy' . $flagsImageExtension ],
					[ 'hk', 'hk', $flagsFolderOrSpritePrefix . 'hk' . $flagsImageExtension ],
					[ 'hm', 'hm', $flagsFolderOrSpritePrefix . 'hm' . $flagsImageExtension ],
					[ 'hn', 'hn', $flagsFolderOrSpritePrefix . 'hn' . $flagsImageExtension ],
					[ 'hr', 'hr', $flagsFolderOrSpritePrefix . 'hr' . $flagsImageExtension ],
					[ 'ht', 'ht', $flagsFolderOrSpritePrefix . 'ht' . $flagsImageExtension ],
					[ 'hu', 'hu', $flagsFolderOrSpritePrefix . 'hu' . $flagsImageExtension ],
					[ 'id', 'id', $flagsFolderOrSpritePrefix . 'id' . $flagsImageExtension ],
					[ 'ie', 'ie', $flagsFolderOrSpritePrefix . 'ie' . $flagsImageExtension ],
					[ 'il', 'il', $flagsFolderOrSpritePrefix . 'il' . $flagsImageExtension ],
					[ 'in', 'in', $flagsFolderOrSpritePrefix . 'in' . $flagsImageExtension ],
					[ 'io', 'io', $flagsFolderOrSpritePrefix . 'io' . $flagsImageExtension ],
					[ 'iq', 'iq', $flagsFolderOrSpritePrefix . 'iq' . $flagsImageExtension ],
					[ 'ir', 'ir', $flagsFolderOrSpritePrefix . 'ir' . $flagsImageExtension ],
					[ 'is', 'is', $flagsFolderOrSpritePrefix . 'is' . $flagsImageExtension ],
					[ 'it', 'it', $flagsFolderOrSpritePrefix . 'it' . $flagsImageExtension ],
					[ 'jm', 'jm', $flagsFolderOrSpritePrefix . 'jm' . $flagsImageExtension ],
					[ 'jo', 'jo', $flagsFolderOrSpritePrefix . 'jo' . $flagsImageExtension ],
					[ 'jp', 'jp', $flagsFolderOrSpritePrefix . 'jp' . $flagsImageExtension ],
					[ 'ke', 'ke', $flagsFolderOrSpritePrefix . 'ke' . $flagsImageExtension ],
					[ 'kg', 'kg', $flagsFolderOrSpritePrefix . 'kg' . $flagsImageExtension ],
					[ 'kh', 'kh', $flagsFolderOrSpritePrefix . 'kh' . $flagsImageExtension ],
					[ 'ki', 'ki', $flagsFolderOrSpritePrefix . 'ki' . $flagsImageExtension ],
					[ 'km', 'km', $flagsFolderOrSpritePrefix . 'km' . $flagsImageExtension ],
					[ 'kn', 'kn', $flagsFolderOrSpritePrefix . 'kn' . $flagsImageExtension ],
					[ 'kp', 'kp', $flagsFolderOrSpritePrefix . 'kp' . $flagsImageExtension ],
					[ 'kr', 'kr', $flagsFolderOrSpritePrefix . 'kr' . $flagsImageExtension ],
					[ 'kw', 'kw', $flagsFolderOrSpritePrefix . 'kw' . $flagsImageExtension ],
					[ 'ky', 'ky', $flagsFolderOrSpritePrefix . 'ky' . $flagsImageExtension ],
					[ 'kz', 'kz', $flagsFolderOrSpritePrefix . 'kz' . $flagsImageExtension ],
					[ 'la', 'la', $flagsFolderOrSpritePrefix . 'la' . $flagsImageExtension ],
					[ 'lb', 'lb', $flagsFolderOrSpritePrefix . 'lb' . $flagsImageExtension ],
					[ 'lc', 'lc', $flagsFolderOrSpritePrefix . 'lc' . $flagsImageExtension ],
					[ 'li', 'li', $flagsFolderOrSpritePrefix . 'li' . $flagsImageExtension ],
					[ 'lk', 'lk', $flagsFolderOrSpritePrefix . 'lk' . $flagsImageExtension ],
					[ 'lr', 'lr', $flagsFolderOrSpritePrefix . 'lr' . $flagsImageExtension ],
					[ 'ls', 'ls', $flagsFolderOrSpritePrefix . 'ls' . $flagsImageExtension ],
					[ 'lt', 'lt', $flagsFolderOrSpritePrefix . 'lt' . $flagsImageExtension ],
					[ 'lu', 'lu', $flagsFolderOrSpritePrefix . 'lu' . $flagsImageExtension ],
					[ 'lv', 'lv', $flagsFolderOrSpritePrefix . 'lv' . $flagsImageExtension ],
					[ 'ly', 'ly', $flagsFolderOrSpritePrefix . 'ly' . $flagsImageExtension ],
					[ 'ma', 'ma', $flagsFolderOrSpritePrefix . 'ma' . $flagsImageExtension ],
					[ 'mc', 'mc', $flagsFolderOrSpritePrefix . 'mc' . $flagsImageExtension ],
					[ 'md', 'md', $flagsFolderOrSpritePrefix . 'md' . $flagsImageExtension ],
					[ 'me', 'me', $flagsFolderOrSpritePrefix . 'me' . $flagsImageExtension ],
					[ 'mg', 'mg', $flagsFolderOrSpritePrefix . 'mg' . $flagsImageExtension ],
					[ 'mh', 'mh', $flagsFolderOrSpritePrefix . 'mh' . $flagsImageExtension ],
					[ 'mk', 'mk', $flagsFolderOrSpritePrefix . 'mk' . $flagsImageExtension ],
					[ 'ml', 'ml', $flagsFolderOrSpritePrefix . 'ml' . $flagsImageExtension ],
					[ 'mm', 'mm', $flagsFolderOrSpritePrefix . 'mm' . $flagsImageExtension ],
					[ 'mn', 'mn', $flagsFolderOrSpritePrefix . 'mn' . $flagsImageExtension ],
					[ 'mo', 'mo', $flagsFolderOrSpritePrefix . 'mo' . $flagsImageExtension ],
					[ 'mp', 'mp', $flagsFolderOrSpritePrefix . 'mp' . $flagsImageExtension ],
					[ 'mq', 'mq', $flagsFolderOrSpritePrefix . 'mq' . $flagsImageExtension ],
					[ 'mr', 'mr', $flagsFolderOrSpritePrefix . 'mr' . $flagsImageExtension ],
					[ 'ms', 'ms', $flagsFolderOrSpritePrefix . 'ms' . $flagsImageExtension ],
					[ 'mt', 'mt', $flagsFolderOrSpritePrefix . 'mt' . $flagsImageExtension ],
					[ 'mu', 'mu', $flagsFolderOrSpritePrefix . 'mu' . $flagsImageExtension ],
					[ 'mv', 'mv', $flagsFolderOrSpritePrefix . 'mv' . $flagsImageExtension ],
					[ 'mw', 'mw', $flagsFolderOrSpritePrefix . 'mw' . $flagsImageExtension ],
					[ 'mx', 'mx', $flagsFolderOrSpritePrefix . 'mx' . $flagsImageExtension ],
					[ 'my', 'my', $flagsFolderOrSpritePrefix . 'my' . $flagsImageExtension ],
					[ 'mz', 'mz', $flagsFolderOrSpritePrefix . 'mz' . $flagsImageExtension ],
					[ 'na', 'na', $flagsFolderOrSpritePrefix . 'na' . $flagsImageExtension ],
					[ 'nc', 'nc', $flagsFolderOrSpritePrefix . 'nc' . $flagsImageExtension ],
					[ 'ne', 'ne', $flagsFolderOrSpritePrefix . 'ne' . $flagsImageExtension ],
					[ 'nf', 'nf', $flagsFolderOrSpritePrefix . 'nf' . $flagsImageExtension ],
					[ 'ng', 'ng', $flagsFolderOrSpritePrefix . 'ng' . $flagsImageExtension ],
					[ 'ni', 'ni', $flagsFolderOrSpritePrefix . 'ni' . $flagsImageExtension ],
					[ 'nl', 'nl', $flagsFolderOrSpritePrefix . 'nl' . $flagsImageExtension ],
					[ 'no', 'no', $flagsFolderOrSpritePrefix . 'no' . $flagsImageExtension ],
					[ 'np', 'np', $flagsFolderOrSpritePrefix . 'np' . $flagsImageExtension ],
					[ 'nr', 'nr', $flagsFolderOrSpritePrefix . 'nr' . $flagsImageExtension ],
					[ 'nu', 'nu', $flagsFolderOrSpritePrefix . 'nu' . $flagsImageExtension ],
					[ 'nz', 'nz', $flagsFolderOrSpritePrefix . 'nz' . $flagsImageExtension ],
					[ 'om', 'om', $flagsFolderOrSpritePrefix . 'om' . $flagsImageExtension ],
					[ 'pa', 'pa', $flagsFolderOrSpritePrefix . 'pa' . $flagsImageExtension ],
					[ 'pe', 'pe', $flagsFolderOrSpritePrefix . 'pe' . $flagsImageExtension ],
					[ 'pf', 'pf', $flagsFolderOrSpritePrefix . 'pf' . $flagsImageExtension ],
					[ 'pg', 'pg', $flagsFolderOrSpritePrefix . 'pg' . $flagsImageExtension ],
					[ 'ph', 'ph', $flagsFolderOrSpritePrefix . 'ph' . $flagsImageExtension ],
					[ 'pk', 'pk', $flagsFolderOrSpritePrefix . 'pk' . $flagsImageExtension ],
					[ 'pl', 'pl', $flagsFolderOrSpritePrefix . 'pl' . $flagsImageExtension ],
					[ 'pm', 'pm', $flagsFolderOrSpritePrefix . 'pm' . $flagsImageExtension ],
					[ 'pn', 'pn', $flagsFolderOrSpritePrefix . 'pn' . $flagsImageExtension ],
					[ 'pr', 'pr', $flagsFolderOrSpritePrefix . 'pr' . $flagsImageExtension ],
					[ 'ps', 'ps', $flagsFolderOrSpritePrefix . 'ps' . $flagsImageExtension ],
					[ 'pt', 'pt', $flagsFolderOrSpritePrefix . 'pt' . $flagsImageExtension ],
					[ 'pw', 'pw', $flagsFolderOrSpritePrefix . 'pw' . $flagsImageExtension ],
					[ 'py', 'py', $flagsFolderOrSpritePrefix . 'py' . $flagsImageExtension ],
					[ 'qa', 'qa', $flagsFolderOrSpritePrefix . 'qa' . $flagsImageExtension ],
					[ 'qc', 'qc', $flagsFolderOrSpritePrefix . 'qc' . $flagsImageExtension ],
					[ 're', 're', $flagsFolderOrSpritePrefix . 're' . $flagsImageExtension ],
					[ 'ro', 'ro', $flagsFolderOrSpritePrefix . 'ro' . $flagsImageExtension ],
					[ 'rs', 'rs', $flagsFolderOrSpritePrefix . 'rs' . $flagsImageExtension ],
					[ 'ru', 'ru', $flagsFolderOrSpritePrefix . 'ru' . $flagsImageExtension ],
					[ 'rw', 'rw', $flagsFolderOrSpritePrefix . 'rw' . $flagsImageExtension ],
					[ 'sa', 'sa', $flagsFolderOrSpritePrefix . 'sa' . $flagsImageExtension ],
					[ 'sb', 'sb', $flagsFolderOrSpritePrefix . 'sb' . $flagsImageExtension ],
					[ 'sc', 'sc', $flagsFolderOrSpritePrefix . 'sc' . $flagsImageExtension ],
					[ 'scotland', 'scotland', $flagsFolderOrSpritePrefix . 'scotland' . $flagsImageExtension ],
					[ 'sd', 'sd', $flagsFolderOrSpritePrefix . 'sd' . $flagsImageExtension ],
					[ 'se', 'se', $flagsFolderOrSpritePrefix . 'se' . $flagsImageExtension ],
					[ 'sg', 'sg', $flagsFolderOrSpritePrefix . 'sg' . $flagsImageExtension ],
					[ 'sh', 'sh', $flagsFolderOrSpritePrefix . 'sh' . $flagsImageExtension ],
					[ 'si', 'si', $flagsFolderOrSpritePrefix . 'si' . $flagsImageExtension ],
					[ 'sj', 'sj', $flagsFolderOrSpritePrefix . 'sj' . $flagsImageExtension ],
					[ 'sk', 'sk', $flagsFolderOrSpritePrefix . 'sk' . $flagsImageExtension ],
					[ 'sl', 'sl', $flagsFolderOrSpritePrefix . 'sl' . $flagsImageExtension ],
					[ 'sm', 'sm', $flagsFolderOrSpritePrefix . 'sm' . $flagsImageExtension ],
					[ 'sn', 'sn', $flagsFolderOrSpritePrefix . 'sn' . $flagsImageExtension ],
					[ 'so', 'so', $flagsFolderOrSpritePrefix . 'so' . $flagsImageExtension ],
					[ 'sr', 'sr', $flagsFolderOrSpritePrefix . 'sr' . $flagsImageExtension ],
					[ 'st', 'st', $flagsFolderOrSpritePrefix . 'st' . $flagsImageExtension ],
					[ 'sv', 'sv', $flagsFolderOrSpritePrefix . 'sv' . $flagsImageExtension ],
					[ 'sy', 'sy', $flagsFolderOrSpritePrefix . 'sy' . $flagsImageExtension ],
					[ 'sz', 'sz', $flagsFolderOrSpritePrefix . 'sz' . $flagsImageExtension ],
					[ 'tc', 'tc', $flagsFolderOrSpritePrefix . 'tc' . $flagsImageExtension ],
					[ 'td', 'td', $flagsFolderOrSpritePrefix . 'td' . $flagsImageExtension ],
					[ 'tf', 'tf', $flagsFolderOrSpritePrefix . 'tf' . $flagsImageExtension ],
					[ 'tg', 'tg', $flagsFolderOrSpritePrefix . 'tg' . $flagsImageExtension ],
					[ 'th', 'th', $flagsFolderOrSpritePrefix . 'th' . $flagsImageExtension ],
					[ 'tj', 'tj', $flagsFolderOrSpritePrefix . 'tj' . $flagsImageExtension ],
					[ 'tk', 'tk', $flagsFolderOrSpritePrefix . 'tk' . $flagsImageExtension ],
					[ 'tl', 'tl', $flagsFolderOrSpritePrefix . 'tl' . $flagsImageExtension ],
					[ 'tm', 'tm', $flagsFolderOrSpritePrefix . 'tm' . $flagsImageExtension ],
					[ 'tn', 'tn', $flagsFolderOrSpritePrefix . 'tn' . $flagsImageExtension ],
					[ 'to', 'to', $flagsFolderOrSpritePrefix . 'to' . $flagsImageExtension ],
					[ 'tr', 'tr', $flagsFolderOrSpritePrefix . 'tr' . $flagsImageExtension ],
					[ 'tt', 'tt', $flagsFolderOrSpritePrefix . 'tt' . $flagsImageExtension ],
					[ 'tv', 'tv', $flagsFolderOrSpritePrefix . 'tv' . $flagsImageExtension ],
					[ 'tw', 'tw', $flagsFolderOrSpritePrefix . 'tw' . $flagsImageExtension ],
					[ 'tz', 'tz', $flagsFolderOrSpritePrefix . 'tz' . $flagsImageExtension ],
					[ 'ua', 'ua', $flagsFolderOrSpritePrefix . 'ua' . $flagsImageExtension ],
					[ 'ug', 'ug', $flagsFolderOrSpritePrefix . 'ug' . $flagsImageExtension ],
					[ 'um', 'um', $flagsFolderOrSpritePrefix . 'um' . $flagsImageExtension ],
					[ 'us', 'us', $flagsFolderOrSpritePrefix . 'us' . $flagsImageExtension ],
					[ 'uy', 'uy', $flagsFolderOrSpritePrefix . 'uy' . $flagsImageExtension ],
					[ 'uz', 'uz', $flagsFolderOrSpritePrefix . 'uz' . $flagsImageExtension ],
					[ 'va', 'va', $flagsFolderOrSpritePrefix . 'va' . $flagsImageExtension ],
					[ 'vc', 'vc', $flagsFolderOrSpritePrefix . 'vc' . $flagsImageExtension ],
					[ 've', 've', $flagsFolderOrSpritePrefix . 've' . $flagsImageExtension ],
					[ 'vg', 'vg', $flagsFolderOrSpritePrefix . 'vg' . $flagsImageExtension ],
					[ 'vi', 'vi', $flagsFolderOrSpritePrefix . 'vi' . $flagsImageExtension ],
					[ 'vn', 'vn', $flagsFolderOrSpritePrefix . 'vn' . $flagsImageExtension ],
					[ 'vu', 'vu', $flagsFolderOrSpritePrefix . 'vu' . $flagsImageExtension ],
					[ 'wales', 'wales', $flagsFolderOrSpritePrefix . 'wales' . $flagsImageExtension ],
					[ 'wf', 'wf', $flagsFolderOrSpritePrefix . 'wf' . $flagsImageExtension ],
					[ 'ws', 'ws', $flagsFolderOrSpritePrefix . 'ws' . $flagsImageExtension ],
					[ 'ye', 'ye', $flagsFolderOrSpritePrefix . 'ye' . $flagsImageExtension ],
					[ 'yt', 'yt', $flagsFolderOrSpritePrefix . 'yt' . $flagsImageExtension ],
					[ 'za', 'za', $flagsFolderOrSpritePrefix . 'za' . $flagsImageExtension ],
					[ 'zm', 'zm', $flagsFolderOrSpritePrefix . 'zm' . $flagsImageExtension ],
					[ 'zw', 'zw', $flagsFolderOrSpritePrefix . 'zw' . $flagsImageExtension ]
				],
				'selicon_cols' => 16,
				'size' => 1,
				'minitems' => 1,
				'maxitems' => 1
			]
		]
	]
];