<?php
if ( !defined ('TYPO3_MODE') ) {
	die ( 'Access denied.' );
}

$flagsFolder = version_compare(TYPO3_branch, '7.1', '>=') ? 'EXT:core/Resources/Public/Icons/Flags/' : 'EXT:t3skin/images/flags/';

return [
	'ctrl' => [
		'title'	=> 'LLL:EXT:ecom_toolbox/Resources/Private/Language/locallang_db.xlf:tx_ecomtoolbox_domain_model_language',
		'label' => 'title',
		'label_alt' => 'flag',
		'label_alt_force' => TRUE,
		'tstamp' => 'tstamp',
		'rootLevel' => 1,
		'crdate' => 'crdate',
		'cruser_id' => 'cruser_id',
		'default_sortby' => 'ORDER BY title',
		'dividers2tabs' => TRUE,
		'typeicon_column' => 'flag',
		'typeicon_classes' => [
			'default' => 'extensions-ecomToolbox-language',
			'mask' => 'flags-###TYPE###'
		],
		'searchFields' => 'title,sys_language,flag,',
		'iconfile' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath( 'ecom_toolbox' ) . 'Resources/Public/Icons/tx_ecomtoolbox_domain_model_language.png'
	],
	'interface' => [
		'showRecordFieldList' => 'title, sys_language, flag',
	],
	'types' => [
		'1' => [ 'showitem' => 'title, sys_language, flag' ]
	],
	'palettes' => [],
	'columns' => [
		'title' => [
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.language',
			'config' => [
				'type' => 'input',
				'size' => '35',
				'max' => '80',
				'eval' => 'trim,required'
			]
		],
		'sys_language' => [
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_tca.xlf:sys_language',
			'config' => [
				'type' => 'select',
				'foreign_table' => 'sys_language',
				'foreign_table_where' => 'ORDER BY sys_language.title',
				'items' => [
					[ 'LLL:EXT:lang/locallang_general.xlf:LGL.allLanguages', -1 ],
					[ 'LLL:EXT:lang/locallang_general.xlf:LGL.default_value', 0 ]
				]
			]
		],
		'flag' => [
			'label' => 'LLL:EXT:lang/locallang_tca.xlf:sys_language.flag',
			'config' => [
				'type' => 'select',
				'items' => [
					[ '', '', '' ],
					[ 'multiple', 'multiple', $flagsFolder . 'multiple.png' ],
					[ 'ad', 'ad', $flagsFolder . 'ad.png' ],
					[ 'ae', 'ae', $flagsFolder . 'ae.png' ],
					[ 'af', 'af', $flagsFolder . 'af.png' ],
					[ 'ag', 'ag', $flagsFolder . 'ag.png' ],
					[ 'ai', 'ai', $flagsFolder . 'ai.png' ],
					[ 'al', 'al', $flagsFolder . 'al.png' ],
					[ 'am', 'am', $flagsFolder . 'am.png' ],
					[ 'an', 'an', $flagsFolder . 'an.png' ],
					[ 'ao', 'ao', $flagsFolder . 'ao.png' ],
					[ 'ar', 'ar', $flagsFolder . 'ar.png' ],
					[ 'as', 'as', $flagsFolder . 'as.png' ],
					[ 'at', 'at', $flagsFolder . 'at.png' ],
					[ 'au', 'au', $flagsFolder . 'au.png' ],
					[ 'aw', 'aw', $flagsFolder . 'aw.png' ],
					[ 'ax', 'ax', $flagsFolder . 'ax.png' ],
					[ 'az', 'az', $flagsFolder . 'az.png' ],
					[ 'ba', 'ba', $flagsFolder . 'ba.png' ],
					[ 'bb', 'bb', $flagsFolder . 'bb.png' ],
					[ 'bd', 'bd', $flagsFolder . 'bd.png' ],
					[ 'be', 'be', $flagsFolder . 'be.png' ],
					[ 'bf', 'bf', $flagsFolder . 'bf.png' ],
					[ 'bg', 'bg', $flagsFolder . 'bg.png' ],
					[ 'bh', 'bh', $flagsFolder . 'bh.png' ],
					[ 'bi', 'bi', $flagsFolder . 'bi.png' ],
					[ 'bj', 'bj', $flagsFolder . 'bj.png' ],
					[ 'bm', 'bm', $flagsFolder . 'bm.png' ],
					[ 'bn', 'bn', $flagsFolder . 'bn.png' ],
					[ 'bo', 'bo', $flagsFolder . 'bo.png' ],
					[ 'br', 'br', $flagsFolder . 'br.png' ],
					[ 'bs', 'bs', $flagsFolder . 'bs.png' ],
					[ 'bt', 'bt', $flagsFolder . 'bt.png' ],
					[ 'bv', 'bv', $flagsFolder . 'bv.png' ],
					[ 'bw', 'bw', $flagsFolder . 'bw.png' ],
					[ 'by', 'by', $flagsFolder . 'by.png' ],
					[ 'bz', 'bz', $flagsFolder . 'bz.png' ],
					[ 'ca', 'ca', $flagsFolder . 'ca.png' ],
					[ 'catalonia', 'catalonia', $flagsFolder . 'catalonia.png' ],
					[ 'cc', 'cc', $flagsFolder . 'cc.png' ],
					[ 'cd', 'cd', $flagsFolder . 'cd.png' ],
					[ 'cf', 'cf', $flagsFolder . 'cf.png' ],
					[ 'cg', 'cg', $flagsFolder . 'cg.png' ],
					[ 'ch', 'ch', $flagsFolder . 'ch.png' ],
					[ 'ci', 'ci', $flagsFolder . 'ci.png' ],
					[ 'ck', 'ck', $flagsFolder . 'ck.png' ],
					[ 'cl', 'cl', $flagsFolder . 'cl.png' ],
					[ 'cm', 'cm', $flagsFolder . 'cm.png' ],
					[ 'cn', 'cn', $flagsFolder . 'cn.png' ],
					[ 'co', 'co', $flagsFolder . 'co.png' ],
					[ 'cr', 'cr', $flagsFolder . 'cr.png' ],
					[ 'cs', 'cs', $flagsFolder . 'cs.png' ],
					[ 'cu', 'cu', $flagsFolder . 'cu.png' ],
					[ 'cv', 'cv', $flagsFolder . 'cv.png' ],
					[ 'cx', 'cx', $flagsFolder . 'cx.png' ],
					[ 'cy', 'cy', $flagsFolder . 'cy.png' ],
					[ 'cz', 'cz', $flagsFolder . 'cz.png' ],
					[ 'de', 'de', $flagsFolder . 'de.png' ],
					[ 'dj', 'dj', $flagsFolder . 'dj.png' ],
					[ 'dk', 'dk', $flagsFolder . 'dk.png' ],
					[ 'dm', 'dm', $flagsFolder . 'dm.png' ],
					[ 'do', 'do', $flagsFolder . 'do.png' ],
					[ 'dz', 'dz', $flagsFolder . 'dz.png' ],
					[ 'ec', 'ec', $flagsFolder . 'ec.png' ],
					[ 'ee', 'ee', $flagsFolder . 'ee.png' ],
					[ 'eg', 'eg', $flagsFolder . 'eg.png' ],
					[ 'eh', 'eh', $flagsFolder . 'eh.png' ],
					[ 'england', 'england', $flagsFolder . 'england.png' ],
					[ 'er', 'er', $flagsFolder . 'er.png' ],
					[ 'es', 'es', $flagsFolder . 'es.png' ],
					[ 'et', 'et', $flagsFolder . 'et.png' ],
					[ 'europeanunion', 'europeanunion', $flagsFolder . 'europeanunion.png' ],
					[ 'fam', 'fam', $flagsFolder . 'fam.png' ],
					[ 'fi', 'fi', $flagsFolder . 'fi.png' ],
					[ 'fj', 'fj', $flagsFolder . 'fj.png' ],
					[ 'fk', 'fk', $flagsFolder . 'fk.png' ],
					[ 'fm', 'fm', $flagsFolder . 'fm.png' ],
					[ 'fo', 'fo', $flagsFolder . 'fo.png' ],
					[ 'fr', 'fr', $flagsFolder . 'fr.png' ],
					[ 'ga', 'ga', $flagsFolder . 'ga.png' ],
					[ 'gb', 'gb', $flagsFolder . 'gb.png' ],
					[ 'gd', 'gd', $flagsFolder . 'gd.png' ],
					[ 'ge', 'ge', $flagsFolder . 'ge.png' ],
					[ 'gf', 'gf', $flagsFolder . 'gf.png' ],
					[ 'gh', 'gh', $flagsFolder . 'gh.png' ],
					[ 'gi', 'gi', $flagsFolder . 'gi.png' ],
					[ 'gl', 'gl', $flagsFolder . 'gl.png' ],
					[ 'gm', 'gm', $flagsFolder . 'gm.png' ],
					[ 'gn', 'gn', $flagsFolder . 'gn.png' ],
					[ 'gp', 'gp', $flagsFolder . 'gp.png' ],
					[ 'gq', 'gq', $flagsFolder . 'gq.png' ],
					[ 'gr', 'gr', $flagsFolder . 'gr.png' ],
					[ 'gs', 'gs', $flagsFolder . 'gs.png' ],
					[ 'gt', 'gt', $flagsFolder . 'gt.png' ],
					[ 'gu', 'gu', $flagsFolder . 'gu.png' ],
					[ 'gw', 'gw', $flagsFolder . 'gw.png' ],
					[ 'gy', 'gy', $flagsFolder . 'gy.png' ],
					[ 'hk', 'hk', $flagsFolder . 'hk.png' ],
					[ 'hm', 'hm', $flagsFolder . 'hm.png' ],
					[ 'hn', 'hn', $flagsFolder . 'hn.png' ],
					[ 'hr', 'hr', $flagsFolder . 'hr.png' ],
					[ 'ht', 'ht', $flagsFolder . 'ht.png' ],
					[ 'hu', 'hu', $flagsFolder . 'hu.png' ],
					[ 'id', 'id', $flagsFolder . 'id.png' ],
					[ 'ie', 'ie', $flagsFolder . 'ie.png' ],
					[ 'il', 'il', $flagsFolder . 'il.png' ],
					[ 'in', 'in', $flagsFolder . 'in.png' ],
					[ 'io', 'io', $flagsFolder . 'io.png' ],
					[ 'iq', 'iq', $flagsFolder . 'iq.png' ],
					[ 'ir', 'ir', $flagsFolder . 'ir.png' ],
					[ 'is', 'is', $flagsFolder . 'is.png' ],
					[ 'it', 'it', $flagsFolder . 'it.png' ],
					[ 'jm', 'jm', $flagsFolder . 'jm.png' ],
					[ 'jo', 'jo', $flagsFolder . 'jo.png' ],
					[ 'jp', 'jp', $flagsFolder . 'jp.png' ],
					[ 'ke', 'ke', $flagsFolder . 'ke.png' ],
					[ 'kg', 'kg', $flagsFolder . 'kg.png' ],
					[ 'kh', 'kh', $flagsFolder . 'kh.png' ],
					[ 'ki', 'ki', $flagsFolder . 'ki.png' ],
					[ 'km', 'km', $flagsFolder . 'km.png' ],
					[ 'kn', 'kn', $flagsFolder . 'kn.png' ],
					[ 'kp', 'kp', $flagsFolder . 'kp.png' ],
					[ 'kr', 'kr', $flagsFolder . 'kr.png' ],
					[ 'kw', 'kw', $flagsFolder . 'kw.png' ],
					[ 'ky', 'ky', $flagsFolder . 'ky.png' ],
					[ 'kz', 'kz', $flagsFolder . 'kz.png' ],
					[ 'la', 'la', $flagsFolder . 'la.png' ],
					[ 'lb', 'lb', $flagsFolder . 'lb.png' ],
					[ 'lc', 'lc', $flagsFolder . 'lc.png' ],
					[ 'li', 'li', $flagsFolder . 'li.png' ],
					[ 'lk', 'lk', $flagsFolder . 'lk.png' ],
					[ 'lr', 'lr', $flagsFolder . 'lr.png' ],
					[ 'ls', 'ls', $flagsFolder . 'ls.png' ],
					[ 'lt', 'lt', $flagsFolder . 'lt.png' ],
					[ 'lu', 'lu', $flagsFolder . 'lu.png' ],
					[ 'lv', 'lv', $flagsFolder . 'lv.png' ],
					[ 'ly', 'ly', $flagsFolder . 'ly.png' ],
					[ 'ma', 'ma', $flagsFolder . 'ma.png' ],
					[ 'mc', 'mc', $flagsFolder . 'mc.png' ],
					[ 'md', 'md', $flagsFolder . 'md.png' ],
					[ 'me', 'me', $flagsFolder . 'me.png' ],
					[ 'mg', 'mg', $flagsFolder . 'mg.png' ],
					[ 'mh', 'mh', $flagsFolder . 'mh.png' ],
					[ 'mk', 'mk', $flagsFolder . 'mk.png' ],
					[ 'ml', 'ml', $flagsFolder . 'ml.png' ],
					[ 'mm', 'mm', $flagsFolder . 'mm.png' ],
					[ 'mn', 'mn', $flagsFolder . 'mn.png' ],
					[ 'mo', 'mo', $flagsFolder . 'mo.png' ],
					[ 'mp', 'mp', $flagsFolder . 'mp.png' ],
					[ 'mq', 'mq', $flagsFolder . 'mq.png' ],
					[ 'mr', 'mr', $flagsFolder . 'mr.png' ],
					[ 'ms', 'ms', $flagsFolder . 'ms.png' ],
					[ 'mt', 'mt', $flagsFolder . 'mt.png' ],
					[ 'mu', 'mu', $flagsFolder . 'mu.png' ],
					[ 'mv', 'mv', $flagsFolder . 'mv.png' ],
					[ 'mw', 'mw', $flagsFolder . 'mw.png' ],
					[ 'mx', 'mx', $flagsFolder . 'mx.png' ],
					[ 'my', 'my', $flagsFolder . 'my.png' ],
					[ 'mz', 'mz', $flagsFolder . 'mz.png' ],
					[ 'na', 'na', $flagsFolder . 'na.png' ],
					[ 'nc', 'nc', $flagsFolder . 'nc.png' ],
					[ 'ne', 'ne', $flagsFolder . 'ne.png' ],
					[ 'nf', 'nf', $flagsFolder . 'nf.png' ],
					[ 'ng', 'ng', $flagsFolder . 'ng.png' ],
					[ 'ni', 'ni', $flagsFolder . 'ni.png' ],
					[ 'nl', 'nl', $flagsFolder . 'nl.png' ],
					[ 'no', 'no', $flagsFolder . 'no.png' ],
					[ 'np', 'np', $flagsFolder . 'np.png' ],
					[ 'nr', 'nr', $flagsFolder . 'nr.png' ],
					[ 'nu', 'nu', $flagsFolder . 'nu.png' ],
					[ 'nz', 'nz', $flagsFolder . 'nz.png' ],
					[ 'om', 'om', $flagsFolder . 'om.png' ],
					[ 'pa', 'pa', $flagsFolder . 'pa.png' ],
					[ 'pe', 'pe', $flagsFolder . 'pe.png' ],
					[ 'pf', 'pf', $flagsFolder . 'pf.png' ],
					[ 'pg', 'pg', $flagsFolder . 'pg.png' ],
					[ 'ph', 'ph', $flagsFolder . 'ph.png' ],
					[ 'pk', 'pk', $flagsFolder . 'pk.png' ],
					[ 'pl', 'pl', $flagsFolder . 'pl.png' ],
					[ 'pm', 'pm', $flagsFolder . 'pm.png' ],
					[ 'pn', 'pn', $flagsFolder . 'pn.png' ],
					[ 'pr', 'pr', $flagsFolder . 'pr.png' ],
					[ 'ps', 'ps', $flagsFolder . 'ps.png' ],
					[ 'pt', 'pt', $flagsFolder . 'pt.png' ],
					[ 'pw', 'pw', $flagsFolder . 'pw.png' ],
					[ 'py', 'py', $flagsFolder . 'py.png' ],
					[ 'qa', 'qa', $flagsFolder . 'qa.png' ],
					[ 'qc', 'qc', $flagsFolder . 'qc.png' ],
					[ 're', 're', $flagsFolder . 're.png' ],
					[ 'ro', 'ro', $flagsFolder . 'ro.png' ],
					[ 'rs', 'rs', $flagsFolder . 'rs.png' ],
					[ 'ru', 'ru', $flagsFolder . 'ru.png' ],
					[ 'rw', 'rw', $flagsFolder . 'rw.png' ],
					[ 'sa', 'sa', $flagsFolder . 'sa.png' ],
					[ 'sb', 'sb', $flagsFolder . 'sb.png' ],
					[ 'sc', 'sc', $flagsFolder . 'sc.png' ],
					[ 'scotland', 'scotland', $flagsFolder . 'scotland.png' ],
					[ 'sd', 'sd', $flagsFolder . 'sd.png' ],
					[ 'se', 'se', $flagsFolder . 'se.png' ],
					[ 'sg', 'sg', $flagsFolder . 'sg.png' ],
					[ 'sh', 'sh', $flagsFolder . 'sh.png' ],
					[ 'si', 'si', $flagsFolder . 'si.png' ],
					[ 'sj', 'sj', $flagsFolder . 'sj.png' ],
					[ 'sk', 'sk', $flagsFolder . 'sk.png' ],
					[ 'sl', 'sl', $flagsFolder . 'sl.png' ],
					[ 'sm', 'sm', $flagsFolder . 'sm.png' ],
					[ 'sn', 'sn', $flagsFolder . 'sn.png' ],
					[ 'so', 'so', $flagsFolder . 'so.png' ],
					[ 'sr', 'sr', $flagsFolder . 'sr.png' ],
					[ 'st', 'st', $flagsFolder . 'st.png' ],
					[ 'sv', 'sv', $flagsFolder . 'sv.png' ],
					[ 'sy', 'sy', $flagsFolder . 'sy.png' ],
					[ 'sz', 'sz', $flagsFolder . 'sz.png' ],
					[ 'tc', 'tc', $flagsFolder . 'tc.png' ],
					[ 'td', 'td', $flagsFolder . 'td.png' ],
					[ 'tf', 'tf', $flagsFolder . 'tf.png' ],
					[ 'tg', 'tg', $flagsFolder . 'tg.png' ],
					[ 'th', 'th', $flagsFolder . 'th.png' ],
					[ 'tj', 'tj', $flagsFolder . 'tj.png' ],
					[ 'tk', 'tk', $flagsFolder . 'tk.png' ],
					[ 'tl', 'tl', $flagsFolder . 'tl.png' ],
					[ 'tm', 'tm', $flagsFolder . 'tm.png' ],
					[ 'tn', 'tn', $flagsFolder . 'tn.png' ],
					[ 'to', 'to', $flagsFolder . 'to.png' ],
					[ 'tr', 'tr', $flagsFolder . 'tr.png' ],
					[ 'tt', 'tt', $flagsFolder . 'tt.png' ],
					[ 'tv', 'tv', $flagsFolder . 'tv.png' ],
					[ 'tw', 'tw', $flagsFolder . 'tw.png' ],
					[ 'tz', 'tz', $flagsFolder . 'tz.png' ],
					[ 'ua', 'ua', $flagsFolder . 'ua.png' ],
					[ 'ug', 'ug', $flagsFolder . 'ug.png' ],
					[ 'um', 'um', $flagsFolder . 'um.png' ],
					[ 'us', 'us', $flagsFolder . 'us.png' ],
					[ 'uy', 'uy', $flagsFolder . 'uy.png' ],
					[ 'uz', 'uz', $flagsFolder . 'uz.png' ],
					[ 'va', 'va', $flagsFolder . 'va.png' ],
					[ 'vc', 'vc', $flagsFolder . 'vc.png' ],
					[ 've', 've', $flagsFolder . 've.png' ],
					[ 'vg', 'vg', $flagsFolder . 'vg.png' ],
					[ 'vi', 'vi', $flagsFolder . 'vi.png' ],
					[ 'vn', 'vn', $flagsFolder . 'vn.png' ],
					[ 'vu', 'vu', $flagsFolder . 'vu.png' ],
					[ 'wales', 'wales', $flagsFolder . 'wales.png' ],
					[ 'wf', 'wf', $flagsFolder . 'wf.png' ],
					[ 'ws', 'ws', $flagsFolder . 'ws.png' ],
					[ 'ye', 'ye', $flagsFolder . 'ye.png' ],
					[ 'yt', 'yt', $flagsFolder . 'yt.png' ],
					[ 'za', 'za', $flagsFolder . 'za.png' ],
					[ 'zm', 'zm', $flagsFolder . 'zm.png' ],
					[ 'zw', 'zw', $flagsFolder . 'zw.png' ]
				],
				'selicon_cols' => 16,
				'size' => 1,
				'minitems' => 1,
				'maxitems' => 1
			]
		]
	]
];