<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ecom_toolbox"
 *
 * Auto generated by Extension Builder 2015-04-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ecom Toolbox',
	'description' => 'Provides useful tools for and from ecom.',
	'category' => 'plugin',
	'author' => 'Nicolas Scheidler, Sebastian Iffland',
	'author_email' => 'Nicolas.Scheidler@ecom-ex.com, sebastian.iffland@ecom-ex.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);